### ISSUE TITLE
这个问题怎么解决

### ISSUE THREAD

**Issue by userInner** [hyperbench/hyperbench#51]
[blockchain][ERROR] 10:37:45.853 blockchain.go:39 plugin failed: plugin.Open("./hyperchain"): plugin was built with a different version of package golang.org/x/sys/internal/unsafeheader

**Comment by liuxiaomeiG** [comment]
确认hyperbench仓库中go.mod和hyperbench-plugins中对应插件库中引用的 `golang.org/x/sys` 版本一致，出现这个问题是因为两个库中引用的这个库版本不一致导致的。 

另外也可以按照hyperbench readMe中hyperbench与hyperbench-plugin的版本对应关系，拉取对应版本的代码，不要执行go mod tidy，直接make build。推上去的代码提前核对了各个库的版本。如果有误，可采用上述方式对提示不同版本的库进行版本核对和修改

**Comment by userInner** [comment]
root@tmd-QiTianM610-N000:/gopath/src/t/hyperbench# make build
/gopath/pkg/mod/github.com/influxdata/influxdb-client-go/v2@v2.10.0/api/users.go:17:2: missing go.sum entry for module providing package golang.org/x/net/publicsuffix (imported by github.com/influxdata/influxdb-client-go/v2/api); to add:
	go get github.com/influxdata/influxdb-client-go/v2/api@v2.10.0
/gopath/pkg/mod/github.com/go-playground/validator/v10@v10.6.1/baked_in.go:21:2: missing go.sum entry for module providing package golang.org/x/text/language (imported by github.com/go-playground/validator/v10); to add:
	go get github.com/go-playground/validator/v10@v10.6.1
/gopath/pkg/mod/github.com/spf13/afero@v1.8.2/util.go:28:2: missing go.sum entry for module providing package golang.org/x/text/transform (imported by github.com/spf13/afero); to add:
	go get github.com/spf13/afero@v1.8.2
/gopath/pkg/mod/github.com/spf13/afero@v1.8.2/util.go:29:2: missing go.sum entry for module providing package golang.org/x/text/unicode/norm (imported by github.com/spf13/afero); to add:
	go get github.com/spf13/afero@v1.8.2
Error: exit status 1
Usage:
  packr2 build [flags]

Flags:
  -h, --help   help for build

Global Flags:
      --ignore-imports     when set to true packr won't resolve imports for boxes
      --legacy             uses the legacy resolution and packing system (assumes first arg || pwd for input path)
      --silent             silences all output
      --store-cmd string   sub command to use for packing
  -v, --verbose            enables verbose logging

make: *** [Makefile:34: build] Error 1
root@tmd-QiTianM610-N000:/gopath/src/t/hyperbench# 
直接执行make build，报了如上错误

**Comment by userInner** [comment]
[blockchain][ERROR] 18:19:07.866 blockchain.go:46 plugin failed: plugin.Open("./hyperchain"): plugin was built with a different version of package golang.org/x/sys/internal/unsafeheader 
[cmd][CRITI] 18:19:07.867 cobra.go:162 can not create controller: can not create master: can not create local master: load script fail: runtime error: invalid memory address or nil pointer dereference
stack traceback:
	[G]: in function 'new'
	benchmark/hyperchain/local/script.lua:1: in main chunk
又是这个错误了

**Comment by liuxiaomeiG** [comment]
确认hyperbench仓库中go.mod和hyperbench-plugins中对应插件库中引用的 golang.org/x/sys 版本一致，出现这个问题是因为两个库中引用的这个库版本不一致导致的

**Comment by userInner** [comment]
请问如何修改。

**Comment by userInner** [comment]
已经解决了姐，谢谢您

**Comment by liuxiaomeiG** [comment]
因为用插件连接各平台的，所以出现类似 `plugin was built with a different version of package xxxx` 的问题基本都是hyperbench仓库中go.mod与hyperbench-plugins中对应插件库中的go.mod引用的对应依赖库的版本不一致导致的，一般都是低版本向高版本对其。当然，也可能出现高版本的库不支持的情况，这个时候就需要高版本向低版本对其，可以借助replace进行。

**Comment by yuzy0208** [comment]
> 因为用插件连接各平台的，所以出现类似 `plugin was built with a different version of package xxxx` 的问题基本都是hyperbench仓库中go.mod与hyperbench-plugins中对应插件库中的go.mod引用的对应依赖库的版本不一致导致的，一般都是低版本向高版本对其。当然，也可能出现高版本的库不支持的情况，这个时候就需要高版本向低版本对其，可以借助replace进行。

你好，请问这个错误呢？我在hyperbench-plugins中也没找到google.golang.org/protobuf这个的版本配置。
[blockchain][ERROR] 10:36:17.845 blockchain.go:46 plugin failed: plugin.Open("./fabric"): plugin was built with a different version of package google.golang.org/protobuf/internal/detrand 
[cmd][CRITI] 10:36:17.846 cobra.go:162 can not create controller: can not create master: can not create local master: load script fail: runtime error: invalid memory address or nil pointer dereference
stack traceback:
	[G]: in function 'new'
	benchmark/fabric/example/script.lua:3: in main chunk
	[G]: ?
